#define X )*2+1
#define _ )*2
#define s ((((((((0
/*宏定义，用以形象化定义点阵字，8bit*/

const char Gui_phonetic[11][16] =
{ //对音标点阵进行了细节上的修正，用更形象的方法表示
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ X X X X _ _,
	s _ X X _ _ X X _,
	s _ X X _ _ _ _ _,
	s _ _ X X X X _ _,
	s _ X X _ _ _ _ _,
	s _ X X _ _ X X _,
	s _ _ X X X X _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	/* air */

	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ X X X X _ _,
	s _ X X _ _ X X _,
	s _ _ _ _ _ X X _,
	s _ _ _ _ _ X X _,
	s _ _ _ _ _ X X _,
	s _ X X _ _ X X _,
	s _ _ X X X X _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	/* gargle */

	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ X X X X _ _,
	s _ X X _ _ X X _,
	s _ _ _ X X X X _,
	s _ _ X X _ X X _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ _ X X X _ X _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	/* out */

	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ X X X X _ _,
	s _ X X _ _ X X _,
	s _ _ _ _ _ X X _,
	s _ X X X X X X _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ _ X X X X _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	/* alone */

	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ X X _ _ _,
	s _ _ _ X X _ _ _,
	s _ _ X X X X _ _,
	s _ _ X _ _ X _ _,
	s _ X X _ _ X X _,
	s _ X _ _ _ _ X _,
	s X X _ _ _ _ X X,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	/* cup */

	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ X X X X _ _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ X X X X X X _,
	s _ X X X X X X _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ _ X X X X _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	/* thin */

	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ X X X _ X X _,
	s _ _ _ X X X _ _,
	s _ X X X X X _ _,
	s _ _ _ _ _ X X _,
	s _ _ X X X X X _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ _ X X X X _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	/* this */

	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ X X X _,
	s _ _ _ X X _ _ _,
	s _ _ _ X X _ _ _,
	s _ _ _ X X _ _ _,
	s _ _ _ X X _ _ _,
	s _ _ _ X X _ _ _,
	s _ _ _ X X _ _ _,
	s _ _ _ X X _ _ _,
	s _ _ _ X X _ _ _,
	s _ _ _ X X _ _ _,
	s _ _ _ X X _ _ _,
	s _ X X X _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	/* ship */

	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ X X X X X X _,
	s _ _ _ _ _ X X _,
	s _ _ _ _ X X _ _,
	s _ _ X X X X _ _,
	s _ _ _ _ _ X X _,
	s _ _ _ _ _ X X _,
	s _ _ _ _ _ X X _,
	s _ X X _ _ X X _,
	s _ _ X X X X _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	/* treasure */

	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ X X _ X X _ _,
	s _ X X X X X X _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ X X _ _ X X _,
	s _ _ _ _ _ X X _,
	s _ _ _ _ _ X X _,
	s _ X X _ _ X X _,
	s _ _ X X X X _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	/* sing */

	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s X X X X _ X X _,
	s _ _ _ X X _ _ X,
	s _ _ _ X X _ _ X,
	s _ X X X X X X X,
	s X _ _ X X _ _ _,
	s X _ _ X X _ _ _,
	s X X X X X X X X,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _,
	s _ _ _ _ _ _ _ _
	/* lack */
};

#undef s
#undef X
#undef _

